# Generated by Django 4.0.2 on 2022-03-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.wishlist'),
        ),
    ]
